### PR TITLE
Contrib followup

### PR DESCRIPTION
**Pull request by mpizenberg**
WIP

### CODE REVIEW

**Comment by ryanwebster90** [comment]
can you check your formatting stp?

**Comment by ryanwebster90** [comment]
ok sweet !

**Comment by mpizenberg** [comment]
very WIP

**Comment by mpizenberg** [comment]
Alright it's finally ready for review. Sorry for all the push and the email you must have received. Configuring CI can be annoying since it's not reproducible locally easily.

**Pull request merged**
